name: NEI CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      ALLOWED_HOST: ${{ secrets.ALLOWED_HOST }}
      GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
      GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.prod.yml

      - name: Add Roles
        run: docker-compose exec -T django python manage.py add_roles

      - name: Add Static Data
        run: docker-compose exec -T django python manage.py add_from_json
        
      - name: Run Django Tests
        run: docker-compose exec -T django python manage.py test
        
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          token: ${{ github.token }}
          # Target URL
          target: http://127.0.0.1/
          # Relative path of the ZAP configuration file
          #rules_file_name: # optional
          # The Docker file to be executed
          #docker_name: # default is ghcr.io/zaproxy/zaproxy:stable
          # Additional command line options
          cmd_options: -t http://127.0.0.1/api/openapi/
          # The title for the GitHub issue to be created
          #issue_title: # optional, default is ZAP Full Scan Report
          # The action status will be set to fail if ZAP identifies any alerts during the full scan
          #fail_action: # optional
          # Whether Github issues should be created or not
          #allow_issue_writing: # optional, default is true
          # The name of the artifact that contains the ZAP reports
          #artifact_name: # optional, default is zap_scan
          
      - name: Clean up
        run: docker-compose down --remove-orphans --volumes
